### ISSUE TITLE
2.2.0 fails with Commander 6.0

### ISSUE THREAD

**Issue by gmaxey** [electriccommunity/ec-pipeline-activity#34]
"class com.google.gwt.core.client.JavaScriptException: (TypeError): Cannot read property 'b' of null.

Here's the URL used which works for version 2.1.0:

https://flow/commander/pages/PipelineActivity/activity?projectName=Heat%20Clinic&workflowDefinitionName=Development%20Pipeline

**Comment by lrochette** [comment]
it also fails in Italy with 6.0.1.
I think it simply needs to be rebuild

**Comment by lrochette** [comment]
I tried to build it but get the error

buildJavascript.run:
     [java] Loading inherited module 'ecplugins.PipelineActivity.PipelineActivityComponent'
     [java]    Loading inherited module 'ca.nanometrics.gflot.GFlot'
     [java]       [ERROR] Unable to find 'ca/nanometrics/gflot/GFlot.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
     [java]    [ERROR] Line 9: Unexpected exception while processing element 'inherits'
     [java] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)

I've the SDK 6.0.1

**Comment by lrochette** [comment]
The error is due to the missing gflot package. You should provide it as part of your source tree if you need it.
I'll add it

**Comment by lrochette** [comment]
Fixed in version 2.6.0
